### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by aikar** [aikar/commands#1]
Aikar Commands is lame

Ideas for name of project?

**Comment by MitchDevelopment** [comment]
AiCommands? :P

**Comment by willies952002** [comment]
how about "CommandCore"?

**Comment by aikar** [comment]
Another suggestion received on IRC was "ACF" = Aikar Command Framework from Frostalf

**Comment by simpleauthority** [comment]
I personally think ACF is pretty good.

**Comment by aikar** [comment]
ACF it will be.
