### ISSUE TITLE
[JDA/Contexts] Resolving issue

### ISSUE THREAD

**Issue by Proximyst** [aikar/commands#113]
In the current state, contexts' message contents are gotten from Message#getContentDisplay, which has the following JavaDocs:
```
The textual content of this message in the format that would be shown to the Discord client.
All IMentionable entities will be resolved to the format shown by the Discord client instead of the <id> format.
This includes resolving:
 - Users / Members to their @Username/@Nickname format,
 - TextChannels to their #ChannelName format,
 - Roles to their @RoleName format Emotes (not emojis!) to their :name: format.
If you want the actual Content (mentions as <@id>), use getContentRaw() instead
```
The contexts as of now uses the following "pattern" of resolving all the stated: (snippet from the context of User)
```java
if (arg.startsWith("@")) {
    user = jda.getUserById(arg.substring(1));
} else {
    List<User> users = jda.getUsersByName(arg, true);
    if (!users.isEmpty()) {
        user = users.get(0);
    }
}
```
As it resolves this, it'd find `@proximyayst#0001`, which it would try to resolve. `#getUserById` fails to do so and throws an exception, as `proximyayst` is not a Long.

The following options are available in order to fix it, as far as I can see it:
 - Treat the content as raw
 - Parse all users before doing contexts and pass the cache around
 - Use an unsafe method of parsing from username/nickname. This would cause collisions
 - Manually get content in the contexts and rather pass normal and properly formatted messages to all command implementations

**Comment by simpleauthority** [comment]
I don't believe this is still an issue. @Proximyst can you comment?

**Comment by aikar** [comment]
No, this was resolved with proxi's PR, and just didn't close this.
