### ISSUE TITLE
add @Private annotation to hide commands in tabcomplete and help

### ISSUE THREAD

**Issue by MiniDigger** [aikar/commands#123]
Useful for commands triggered by commandblocks or chat events you don't want to player to use directly.

would add a check here https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/BaseCommand.java#L520
and here
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/CommandHelp.java#L67

I this is something we want in acf I can throw together a PR when I get home today.

**Comment by aikar** [comment]
Implemented in #124
