### ISSUE TITLE
Only supports 1.9+

### ISSUE THREAD

**Issue by MitchDevelopment** [aikar/commands#16]
I am aware that support for versions lower than 1.9 is probably not your primary concern, but since 1.8.x versions are still commonly used I thought this should be brought up.

When checking the player's hand for an item, a method only added in 1.9+ is used to obtain the ItemStack object, namely the [PlayerInventory#getItemInMainHand](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/PlayerInventory.html#getItemInMainHand()) method.

Since this method does not exist in 1.8 it will throw a `NoSuchMethodError` at runtime, if used on a server running that version.

The use of the version-incompatible method is located [here](/aikar/commands/blob/master/src/main/java/co/aikar/commands/BukkitCommandContexts.java#L68).

**Comment by aikar** [comment]
there is also a setName issue

We need to use reflection for setname, and i believe we can get item in main hand in a version safe way using selected slot index and player inventory.

**Comment by aikar** [comment]
both issues are resolved now
