### ISSUE TITLE
Remove error messages that aren't errors

### ISSUE THREAD

**Issue by NiklasEi** [aikar/commands#160]
I would like to propose to remove the error messages when command replacements are added after some commands are already registered: https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/CommandReplacements.java#L57-L58

The fact that these replacements will only work for commands registered afterwards makes sense and is not really an error. The additional replacements still work fine for new commands. I am adding commands in add-on plugins and add new replacements for those, but at that point the main plugin already has registered it's own replacements and commands. In a case like this I don't see any reason for these messages.

Optionally one could set it to a log level like FINE, so it still get's printed if one sets the log level lower.

I implemented the last option on my fork, since I didn't want to publish a new version of my plugin with these error messages. If you agree with me on this I can open a PR.

**Comment by aikar** [comment]
How about we make it a little smarter, and simply iterate all the registered commands in the manager and see if its discovered in there.

This way, your use case will be supported, and if someone accidently registers their replacement too late, resulting in a command being broken, it will print the error.

Can you PR that? 

Also re the logging level stuff, I'm now questioning why do we even have our own LogLevel enum, need to just switch to using the raw levels.

**Comment by NiklasEi** [comment]
That would be much better, yes. I'll work on it and open a pull request.
