### ISSUE TITLE
Handle Breaking up Subcommands into multiple classes of same base command

### ISSUE THREAD

**Issue by aikar** [aikar/commands#17]
Have the ability for multiple Command instances to use the same root command.
This is so you can organize your commands such as 

ResdienceCommand
ResidenceAdminCommand

We will accomplish this by not registering the command instances directly to the Command map, and instead a "Forwarding" command.

This forwarding command will contain the subcommand map, and look up the command instance that owns the registered sub command, and forward the call to it.

We need to add a warning if 2 instances try to register the same subcommand

**Comment by TryHardDood** [comment]
> We need to add a warning if 2 instances try to register the same subcommand

`[11:19:53] [Server thread/ERROR]: ACF Error: kit registered subcommand __unknown - but it is already defined in kit`

**onEnable:**
```
this.commandManager = ACF.createManager(this);

this.commandManager.registerCommand(new MainCommand(this));
this.commandManager.registerCommand(new BuyCommand(this));
this.commandManager.registerCommand(new CreateCommand(this));
this.commandManager.registerCommand(new DeleteCommand(this));
this.commandManager.registerCommand(new EditCommand(this));
this.commandManager.registerCommand(new FlagCommand(this));
this.commandManager.registerCommand(new GiveCommand(this));
this.commandManager.registerCommand(new ReloadCommand(this));
this.commandManager.registerCommand(new UseCommand(this));
this.commandManager.registerCommand(new ViewCommand(this));
```

**Commands template:**
- All the classes have the same **@CommandAlias** but the **@Subcommands** are different.
```
@CommandAlias("kit")
public class ViewCommand extends BaseCommand {
	private final Plugin instance;
	private ConcurrentHashMap<UUID, Kit> currentKit = new ConcurrentHashMap<>();

	public ViewCommand(Plugin instance) {
		this.instance = instance;
	}

	@Subcommand("view")
	@Syntax("[value]")
	public void onViewCommand(Player player, @Optional String value) {
	}
}
```

**Comment by aikar** [comment]
Yeah i need to improve the unknown handler stuff. I was going to put in an ignore for that last night but forgot.

**Comment by aikar** [comment]
Filed #27
