### ISSUE TITLE
[Bug] First argument is not being used in default command

### ISSUE THREAD

**Issue by Rushmead** [aikar/commands#170]
What's happening: Registering a command which is the default, the first argument "username" is not being used. We end up with the args list having all the arguments, and username doesn't get passed down at all. Here is an example piece of code and my IDE's debugger values.

![Image of debugger](https://i.imgur.com/6gxpEzG.png)
Example: 
```
@CommandAlias("msg")
public class MessageCommand extends BaseCommand {

    @Default
    public void execute(CommandIssuer sender, String username, String[] args) {
        AsyncDatabase.submit(() -> {
            UUID playerUUID = PlayerManager.getUUIDForUsername(args[0]);
            if(!RedisManager.getPlayers().contains(playerUUID)){
                sender.sendMessage("That player is not online.");
                return;
            }
            StringBuilder stringBuilder = new StringBuilder();
            for(int i = 1; 1 < args.length; i++){
                stringBuilder.append(args[i]).append(" ");
            }
        });
    }
}
```

Hopefully you understand what is happening here.

**Comment by knightzmc** [comment]
This has also happened to me. The only workaround I know of is to add @CatchUnknown and parse username from args[0]

**Comment by Williambraecky** [comment]
You can also use @CommandAlias on the method instead of the class

**Comment by aikar** [comment]
I think this should now be fixed, CommandIssuer was accidently made a required arg, which you were using.

Reopen if it still occurs after pulling latest ACF.

**Comment by Rushmead** [comment]
Hey! Thank's for such a speedy fix! 

It seems to be working fine, but the next problem is that now my last argument isn't getting set. I'm trying to use the behaviour where a string at the end of a method signature will be the rest of the arguments, however, that doesn't seem to be working. I basically want to be able to take all the other arguments and put them into a single string. I've tried using a String[] but that means that username gets set to the command label. Any help would be appreciated. 

```java
@CommandAlias("msg")
    public void onDefault(CommandIssuer sender, String username, String message) {
        AsyncDatabase.submit(() -> {
            UUID playerUUID = PlayerManager.getUUIDForUsername(username);
            if(!RedisManager.getPlayers().contains(playerUUID)){
                sender.sendMessage("That player is not online.");
                return;
            }
        });
    }
```
![Image of debugger](https://i.imgur.com/TDbvK22.png)

**Comment by aikar** [comment]
@Rushmead hmm. that signature should do fine. are you triggering a syntax error, or does it execute with only the first word?

the last string should consume the rest of the input. 

Your signature is definitely valid, but can't think of anything that would of broke final string.

**Comment by Rushmead** [comment]
@aikar It executes with only the first word, I was a little confused as to why it wasn't consuming the rest of the input 🤷‍♂️

**Comment by aikar** [comment]
Can you open a separate issue for that so we can track independently

**Comment by Rushmead** [comment]
Yeah sure! No worrie
