### ISSUE TITLE
[Question] Arguments in commands.

### ISSUE THREAD

**Issue by Andre601** [aikar/commands#171]
This is just a question and not really an issue.

I want to use this framework inside my spigot-plugin, but I'm not sure, how to actually handle arguments in it.
I want to make a command, where people can use the same command in three ways:
1. They just run the command itself without any argument and it shows them all online players.
2. They provide a string after the command and the plugin shows all players that have a name starting with the provided string.
3. They use `group:<groupname>` as an argument and the plugin searches for every player with the given group.

I'm completely new to this and would be happy about any help.

**Comment by aikar** [comment]
Hey there, this is a great example of where ACF shines!

```java
public class MyCommand extends BaseCommand {
    @CommandAlias("foo")
    public void onDefault(Player player) {
       // show all
    }
    @CommandAlias("foo")
    public void onDefault(Player player, PlayerSearcher search) {
        search.getPlayers();
    }
}

public class PlayerSearcher {
    List<Player> players = new ArrayList<>();
    MyPlugin plugin;
    public PlayerSearcher(MyPlugin plugin) {
        this.plugin = plugin;
    }
    public List<Player> getPlayers() {
        return this.players;
    }
    public void search(String search) {
        if (search.startsWith("group:")) {
            searchByGroup(search.substring(6));
        } else {
            searchByName(search);
        }
    }
    public void searchByGroup(String group) {
        //add to players
    }
    public void searchByName(String name) {
        //add to players
    }
}

public class MyPlugin {
    public void onEnable() {
         BukkitCommandManager manager = new BukkitCommandManager(this);
         manager.getCommandContexts().registerContext(PlayerSearcher.class, c -> { 
             PlayerSearcher searcher = new PlayerSearcher();
             searcher.search(c.popFirstArg());
             return searcher;
         });
    }
}
```

Now you can throw PlayerSearcher on any method you need to search for players with, and reuse this logic everywhere.

**Comment by Andre601** [comment]
Alright thanks.

I'll try to add that and probably make some tweaks and changes to it, to make it usable for my thing...
I want collect the playerheads of the command (all players, players starting with arg or with group) and then use it inside a ScrollerInventory.

I let you know, if I have any errors or problems.

**Comment by Andre601** [comment]
I implemented it now, but I'm not 100% sure if I made it correctly or not...
This is my newest commit with the changes: https://github.com/Andre601/HelpGUI/commit/e5185be9ff6f54d2bfd5c0a4d8a7f67fd527dc08

Would be happy about any help there.

**Comment by Andre601** [comment]
I quickly tried and tested it, but it doesn't work for me...

I get this issue here, and honestly have absolutely no idea on how to fix it:
![](https://i.imgur.com/6CzhAHt.png)

I tried everything I can, but that issue still exists...

**Comment by KotlinIsCool** [comment]
You should register the context resolver first and then after that your commands. So try moving [these ](https://github.com/Andre601/HelpGUI/blob/master/src/main/java/com/andre601/helpgui/HelpGUI.java#L34-35)lines below [this ](https://github.com/Andre601/HelpGUI/blob/master/src/main/java/com/andre601/helpgui/HelpGUI.java#L41)line.

**Comment by Andre601** [comment]
I have one more question:
Does ACF already have a predefined message/system for when a command is executed by console?
Like making sure, that only a player can execute the command...

**Comment by aikar** [comment]
Yes, it detects that already, and there is a message entry you can change to change the wording if you wish:
https://github.com/aikar/commands/blob/master/languages/core/acf-core_en.properties#L36

**Comment by Andre601** [comment]
I have some smaller issues:

I tried to use `help.showHelp()` and I got this issue:
![](https://i.imgur.com/cJgGDUB.png)

I then enabled the unstableAPI like described [here]() and now I get this error:
![image](https://user-images.githubusercontent.com/11576465/45453794-2ab26a80-b6e2-11e8-87c5-890042dc48e6.png)

I use the following code:
```java
public class CmdHelpGUI extends BaseCommand {

    @CommandAlias("helpgui")
    @Default
    @HelpCommand
    @CommandPermission("helpgui.help")
    @Description("Shows this help page.")
    public void onHelp(CommandHelp help){
        help.showHelp();
    }

    @Subcommand("reload")
    @Description("Reloads the config.yml")
    @CommandPermission("helpgui.reload")
    public void reloadConfig(Player player){
        LogUtil.INFO("Reloading config.yml...");
        player.sendMessage(ConfigUtil.color(ConfigPaths.MSG_CONFIG_ATTEMPREL));
        HelpGUI.getInstance().reloadConfig();
        LogUtil.INFO("Reload complete!");
        player.sendMessage(ConfigUtil.color(ConfigPaths.MSG_CONFIG_RELOADED));
    }
}
```

**Comment by Andre601** [comment]
The issue was, that I had it at the wrong position in the class....
It's fixed now

**Comment by Andre601** [comment]
Before I close this issue for good: How do the permissions work?
Can I add them to the plugin.yml like normal and then use the `@CommandPermission` annotation for it?

**Comment by darbyjack** [comment]
You do not need them in the plugin.yml. doing that annotation will simply make it so the command checks if they have the permission before running.

**Comment by Andre601** [comment]
Alright thanks.
