### ISSUE TITLE
[Question] What does registerIssuerAwareContext return if issuer is console

### ISSUE THREAD

**Issue by TheCreeperCow** [aikar/commands#175]
Title says all

**Comment by aikar** [comment]
@TheCreeperCow that depends on how you define your resolver. The method only declares expectations of argument consumption to ACF. Aware means you MIGHT consume input. 

Then your context resolver needs to check if its console and determine how it should handle that.

When a resolver is IssuerOnly, ACF knows it will NEVER consume input. when it's a standard resolver, ACF knows it will ALWAYS consume input.

IssuerAware is a "I don't know, varies"
