### ISSUE TITLE
Subcommand Completion

### ISSUE THREAD

**Issue by Zollerboy1** [aikar/commands#183]
Maybe I'm too stupid, but I don't get my command to tab-complete my subcommand names.

For example I have the following command:

```java
@CommandAlias("test")
public class TestCommand extends BaseCommand {

   @Subcommand("bla")
   public final void onBla(CommandSender sender) {
      sender.sendMessage(ChatColor.AQUA + "Bla");
   }

   @Subcommand("lol")
   public void onLOL(CommandSender sender) {
      sender.sendMessage(ChatColor.GREEN + "LOL");
   }
}
```

Plugin:
```java
public final class TestPlugin extends JavaPlugin {

    private PaperCommandManager commandManager;

    @Override
    public void onEnable() {
        this.registerCommands();
    }

    private void registerCommands() {
        this.commandManager = new PaperCommandManager(this);

        this.commandManager.registerCommand(new TestCommand());
    }
}
```

How can I setup completion, so that, when I type `/test` in minecraft, there appear the two completions `bla` and `lol`?

**Comment by aikar** [comment]
this is a known issue im going to be debugging tonight. it actually works on console, just not in game... I gotta figure out what the difference is (I'm actually suspecting bungee might be related)

**Comment by McLive** [comment]
Any progress on this one? :)

**Comment by bshuler** [comment]
While waiting on a fix, moving to BukkitCommandManager is a workaround.

**Comment by js6pak** [comment]
![image](https://user-images.githubusercontent.com/35262707/52171246-ee97a900-2759-11e9-9188-0f6502a2121e.png)
Should it work like that? Or it brigadier bug?

**Comment by aikar** [comment]
@js6pak that bug is on Paper side, I will fix it in Paper soon.

The ACF side of this bug is now resolved.

**Comment by aikar** [comment]
@js6pak please update to Paper 515+ to fix that bug.
