### ISSUE TITLE
Annotation request: Player only.

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#19]
```
@Subcommand("command")
@PlayerOnly
public void onMyCommand(CommandSender sender) {}
```
or
```
@Subcommand("command")
@Only(Sender.PLAYER)
public void onMyCommand(CommandSender sender) {}
```

**Comment by williambraecky** [comment]
You don't need an annotation for this, this can already be achieved by putting Player as the first command argument:
`@Subcommand("foo")
 public void myCommand(Player sender, Foor bar) {}`

**Comment by TryHardDood** [comment]
Allright thanks!

**Comment by aikar** [comment]
Unless the Player is marked @Optional it will tell the console sender "Must be a player to execute this command"

If it is tagged @Optional, Player will be null.

**Comment by aikar** [comment]
This is also why we have OnlinePlayer class - it's the counterpart when looking up another player, since Player is considered "The sender"

I still need to document that.

**Comment by TryHardDood** [comment]
Thank you for the clarification! :)
