### ISSUE TITLE
Unknown command upon supplying arguments

### ISSUE THREAD

**Issue by Proximyst** [aikar/commands#192]
When the signature of the command is as follows:
```java
@Default
public void test(Player sender, String string, @Default("1") int integer) {
```

1. The command returns proper usage on `/test`;
1. The command returns `Unknown Command, please type /help` upon supplying one or both the arguments required in the correct type (`/test clickyclacky` returns this, and same with `/test clickyclacky 3`).

This is with acf-paper 0.5.0-SNAPSHOT.

**Comment by aikar** [comment]
does it behave if you remove the Default?

**Comment by Proximyst** [comment]
If I remove the default on the parameter, I get the exact same behaviour.
