### ISSUE TITLE
@Description adds description to command in Bukkit's /help

### ISSUE THREAD

**Issue by T3hBrian** [aikar/commands#199]
Currently if you register a command with ACF, even if you add a @Description annotation it shows up as blank. For example, with this code:

```
    @CommandAlias("fly")
    @CommandPermission("plugin.fly")
    @Description("Fly command.")
    public void onFoo(Player player) {
        player.setAllowFlight(true);
    }
```

You only see this in game:
![Minecraft Screenshot](https://user-images.githubusercontent.com/32250137/53753214-b087c500-3e7e-11e9-86da-dd4533c5e3a7.png)
It would be nice if it instead showed what the @Description was set to.

**Comment by aikar** [comment]
this was added
