### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Shawn11564** [aikar/commands#203]
I'm new to using acf, when I tried to load my plugin I got an error.

Here is the error I get on load:
https://hastebin.com/otocopetez.sql

Here is my pom.xml: https://hastebin.com/ucifafanav.xml
And this is my build structure: https://gyazo.com/12c1ddfb5130b55686051f805681510d

Am I shading wrong?

**Comment by JOO200** [comment]
Do you build your plugin with the maven task from shadowJar or with the build tool from IntelliJ?

I use gradle instead and I don't have any messages in the Artifacts tab in IntelliJ in my test project.

**Comment by Shawn11564** [comment]
I just use the build tool in IntelliJ

**Comment by Shawn11564** [comment]
Swapping over to gradle, now ACF isn't getting imported...
Here is my build.gradle https://hastebin.com/unaqodepas.gradle

**Comment by MrIvanPlays** [comment]
When maven, you should build via maven ('mvn package') to get ACF shaded into your jar. If you use build artifacts, that won't shade it inside your jar and then won't load.

**Comment by EsGibtKeineMitte** [comment]
I think aikar should make a public pom.xml to make it easier to understand how to shade the libary in the jar file.
Anyone a working pom.xml to work with the commandframework?

**Comment by TehNeon** [comment]
> I think aikar should make a public pom.xml to make it easier to understand how to shade the libary in the jar file.
> Anyone having an working pom.xml to work with the commandframework?

This really isn't needed it you follow the maven setup guide within the wiki: 
https://github.com/aikar/commands/wiki/Maven-Setup

**Comment by EsGibtKeineMitte** [comment]
I have done^^
I have fixt this issue by building an jar-with dependency's.

**Comment by aikar** [comment]
There is an example pom :)
https://github.com/aikar/commands/blob/master/example/pom.xml

Seems issues have been resolved. Please ask for help on discord if need further assistance.
