### ISSUE TITLE
Username too short needed?

### ISSUE THREAD

**Issue by baticag** [aikar/commands#226]
I am using SkinsRestorer and they are using your library for their commands.

Why do you check minimum length of player's name since I have players that are named only with 2 letter names, for example: "ez"?

Because of that check commands fail to execute and I cannot set skin to that player.
Can you please check that or make it configurable?

**Comment by chickeneer** [comment]
I will look into that - give me a bit to pull the code.
Do you mind checking if `ez_` works. Will still look into it, just getting a strange recollection that might work.

**Comment by baticag** [comment]
Don't think that usernames lower than 3 characters work, like it is set on this line for BungeeCord https://github.com/aikar/commands/blob/786ebe831f1ccbc5df852b28f4189e3a34f816a2/bungee/src/main/java/co/aikar/commands/ACFBungeeUtil.java#L115

**Comment by baticag** [comment]
I think that this new commit still doesn't allow nickname "ez"

**Comment by chickeneer** [comment]
I have deployed a fix for this issue. The author of SkinsRestorer will need to release an update to their code to make it work.

Could you explain? "ez" is definitely not shorter than 2 characters.

**Comment by baticag** [comment]
Yeah my mistake sorry, you are right, thank you very much for fix! :)

**Comment by chickeneer** [comment]
No worries. It was actually something that was fixed for the Bukkit implementation already. Not all fixes have propagated to the other implementations.
https://github.com/aikar/commands/pull/133
