### ISSUE TITLE
[Question] Is it possible to not include unecessary files in jar?

### ISSUE THREAD

**Issue by EarlyPacker** [aikar/commands#229]
Hello, I don't know much much about maven, but I was wondering if it is possible to only shade in the jar the classes that are used.
The file when compiling with ACF contains a lot of unnecessary files.
If not, at least the .property files would be nice to not include.

**Comment by MiniDigger** [comment]
refer to the documentation of the shade plugin to learn how you include or exclude files. 
https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html

just note that you actually need at least two of the property files (one for each resource bundle) or acf will not be able to send any messages.

**Comment by aikar** [comment]
these files are not large... please don't increase complexity for no real gain.
