### ISSUE TITLE
Add commands registered with @CommandAlias to /help <plugin_name>.

### ISSUE THREAD

**Issue by ItsTehBrian** [aikar/commands#230]
Currently, if you do `/help <plugin_name>` (`/bukkit:help <plugin_name`) it shows that there is no help for that plugin. This is very unfortunate as the only other ways of telling players about the plugin's available root (@CommandAlias) commands is by explicitly telling them, or them having to search through all of the pages of `/help` (`/bukkit:help`) and looking for the commands that they know are added by the plugin.

I understand that there would be no good way to organize commands registered with `@Subcommand` however all root commands (`@CommandAlias`) should be listed and your plugin name should appear in `/help` (`bukkit:help`).

Thanks.

**Comment by aikar** [comment]
Already supported but is behind the help unstable flag: https://github.com/aikar/commands/wiki/Command-Help

But at this point, you can consider it safe to use help.
