### ISSUE TITLE
[Question] is it possible to turn off "[ACF] Enabled Asynchronous Tab Completion Support!" Message?

### ISSUE THREAD

**Issue by EarlyPacker** [aikar/commands#231]
Hello, when the plugin starts it says in console "[ACF] Enabled Asynchronous Tab Completion Support!" is it possible to turn that off? If not that's fine.

**Comment by chickeneer** [comment]
That is not currently configurable.
https://github.com/aikar/commands/blob/a0b9fb637debbf0829d8d87a27400094595c5410/paper/src/main/java/co/aikar/commands/PaperAsyncTabCompleteHandler.java#L40
