### ISSUE TITLE
No "other" flag on OfflinePlayer (Bukkit)

### ISSUE THREAD

**Issue by Proximyst** [aikar/commands#244]
There's no such thing as an `@Flags("other")` for `OfflinePlayer`, leaving me having to recreate the functionality manually. This same issue is there for `OnlinePlayer[]`, however that might more be worth recreating manually, even though convenience would allow for the flag.

**Comment by JOO200** [comment]
Why do you need the Flag "other"?

The Flag other is only for "Player" from Bukkit. The default behavior is to use the executing player as "Player" argument, the flag other tells acf to use an argument for that.

**Comment by aikar** [comment]
As joo said, what you are asking doesn't make sense. Player object defaulted to the sender of the command, offline player does not, so the concept of other does not exists.

**Comment by Proximyst** [comment]
Ah, I'm sorry, I misunderstood the default action ^^
