### ISSUE TITLE
java.lang.NoSuchMethodError CommandTiming

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#26]
Successfully shaded the dependencies but there's one missing class.
`Caused by: java.lang.NoSuchMethodError: hu.tryharddevs.advancedkits.utils.timings.lib.TimingManager.of(Ljava/lang/String;)Lhu/tryharddevs/advancedkits/utils/timings/lib/CommandTiming;`

![image](https://cloud.githubusercontent.com/assets/10364896/25721071/75abbc9e-310f-11e7-83a1-96cf64d78054.png)

**Comment by aikar** [comment]
Well then! Looks like I forgot to deploy after renaming that class.

Please recompile w/ fresh snapshots (-U in maven, w/e it is for Gradle)

I just re-deployed

**Comment by MiniDigger** [comment]
its  --refresh-dependencies in gradle

**Comment by TryHardDood** [comment]
Fixed
