### ISSUE TITLE
[Request] Command prompter supported dispatch system

### ISSUE THREAD

**Issue by CalmProton** [aikar/commands#274]
## Context
I use command prompter a lot for custom GUI's. It is a vital plugin for my server.
The problem is that plugins that use this library (guilds), are not working properly. 

## Possible Implementation
The way plugin dispatches commands should be changed. Developer of command prompter says that in [plugin page](https://www.spigotmc.org/resources/commandprompter.47772/). (It works with most plugins, but in Guilds, it sends a bad syntax error when I prompt command, and then works when i fill in stuff. 

I am not a coder, so I apologize if some of things i say are stupid.

**Comment by aikar** [comment]
This is not something for ACF. If ACF commands do not work on that plugin, then that plugin is doing something wrong and needs to fix it.

**Comment by aikar** [comment]
Also I think there is some confusion. ACF does not dispatch commands. It is the receiver of a dispatched command.

**Comment by CalmProton** [comment]
@darbyjack regarding this [issue](https://github.com/guilds-plugin/Guilds/issues/345)
