### ISSUE TITLE
Add plugin-provided messages

### ISSUE THREAD

**Issue by Leonardo-DGS** [aikar/commands#276]
Add the possibility to not get included all ACF `.properties` file into the plugin jar and, instead, using messages provided by the plugin (maybe loaded from a YAML file), so you aren't obliged to use predefined messages like those with `acf-core` or `acf-minecraft` prefixes.

**Comment by aikar** [comment]
this is already possible. manager.getLocales()
and https://github.com/aikar/commands/wiki/Locales

You can tell your build script to exclude ACF's property files.

**Comment by Leonardo-DGS** [comment]
@aikar I already know that class.
it's possible to not get included `.properties` default language files in the plugin jar?
I asked if were possible to use custom yaml key prefixes, like `acf-core` or `acf-minecraft`.
