### ISSUE TITLE
[Brigadier] , and other characters cause commands to show as invalid on client

### ISSUE THREAD

**Issue by jpenilla** [aikar/commands#286]
When using the unstable Brigadier API, characters like ``,()[];`` and etc in an argument cause issues. Once the user types one of those characters in an argument, it makes the whole command red and says invalid (even though running it works). A greedy string as the last arg doesn't have this issue but every other type seems to. An example in vanilla acf where this can be seen is with the default OnlinePlayer[].class resolver which will error (show the red command) on the client once you put the ``,`` after the first username, even though the command will properly run and resolve the comma separated list of OnlinePlayer.

Demo with Brigadier on: https://streamable.com/sgfjc1
Demo with Brigadier off: https://streamable.com/ieeblo

**Comment by aikar** [comment]
This is likely not fixable, sounds like a client bug :/ 
There's nothing else but String we can send to client, and im not sure why the client would do this for String.

**Comment by jmanpenilla** [comment]
Hmm... after further investigation I found some more weird behavior. 
* Putting ``"`` around the OnlinePlayer[] arg made the commas allowed (not red)
* By switching the order of the args to be ``String, OnlinePlayer[]`` It allowed commas in the OnlinePlayer[] last arg
  * Replacing String with a quoted string with [this resolver](https://paste.gg/p/anonymous/eb8acf728abf4b0b8c7b375076018faf) results in the OnlinePlayer[] last arg showing red when having a comma without being in quotes
* Sometimes giving a command incorrect args from the CommandAlias will give unknown command, and giving the SubCommand incorrect args will give the right incorrect args message

I think your probably right that it's a client side issue. Probably something to do with ACF's way of handling commands being very different from brigadiers. For reference some vanilla commands take commas in their args but the client gives errors/red text if they are in an incorrect position.

**Comment by jpenilla** [comment]
Closing as this issue isn't fixable; it's due to how Brigadier works and the fact that we cannot register new brig argument types server-side only. *Maybe* in the future, changes to brig could allow for fixing this, but as it stands this issue isn't really fixable.
