### ISSUE TITLE
acf-paper overlaping resource when using Maven

### ISSUE THREAD

**Issue by realkarmakun** [aikar/commands#287]
I'm a beginner when working with maven and after moving to ACF I got following message when building package:
```
[MY_PLUGIN].jar, acf-paper-0.5.0-SNAPSHOT.jar define 1 overlapping resource: 
  - META-INF/MANIFEST.MF
maven-shade-plugin has detected that some class files are
present in two or more JARs. When this happens, only one
single version of the class is copied to the uber jar.
Usually this is not harmful and you can skip these warnings,
otherwise try to manually exclude artifacts based on
mvn dependency:tree -Ddetail=true and the above output.
See http://maven.apache.org/plugins/maven-shade-plugin/

```
I'm not sure what to do. Even if it's harmless I'd like to solve this. Also this message appeared after adding ACF as dependency so I believe it is appropriate to submit issue here.

EDIT: Also I'd like to mention that my plugin works as intended without any issues, but I still want a clear console when I'm building my plugin.

**Comment by portlek** [comment]
It's not important.

**Comment by aikar** [comment]
youll have to consult the internet for help on this, as this doesn't relate to ACF, just a detail of java and shading.

You can likely do as it said and add exclusion rules to shade, but i would suggest just ignoring it.

**Comment by rtxa** [comment]
In case someone wants a solution for this warning:
```xml
                    <filters>
                        <filter>
                            <artifact>co.aikar:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.MF</exclude>
                            </excludes>
                        </filter>
                    </filters>
```
This goes inside of `configuration`
