### ISSUE TITLE
Startup NullPointerException for plugins without special log prefix

### ISSUE THREAD

**Issue by Archy-X** [aikar/commands#293]
NullPointerException on plugin startup after updating the repository with the new commits.
Nothing about ACF was changed in my plugin, it was working right before IntelliJ redownloaded at midnight and errored after.

https://hastebin.com/yecoyexube.cs

It disables my plugin, and the line is on my main class that errors is when a PaperCommandManager is instantiated.

**Comment by applenick** [comment]
Just wanted to say, had the exact same error occur right now. Would be nice to have this fixed asap.

**Comment by JOO200** [comment]
https://github.com/aikar/commands/commit/fd25a31c637843a284d8a17cd6f66d30e72a0f0f#diff-b924ce796882065a044da807232ef5b2
getPrefix is Nullable and it's null if no prefix is set in the plugin.yml from the plugin.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/PluginDescriptionFile.html#getPrefix()
We should check for null and use the plugin name if the prefix is null.

**Comment by Archy-X** [comment]
Issue is fixed when specifying a "prefix" entry in plugin.yml, just confirmed. However, prefix is not required in plugin.yml so this is still a bug.

**Comment by lewysDavies** [comment]
I am also experiencing this issue and as a prefix is optional, agree it should support not having one. Like said before, work arround is to specify a prefix for now.

**Comment by aikar** [comment]
fixed, refresh snapshot versions (See FAQ) to pull update if you aren't getting it yet.
