### ISSUE TITLE
[QUESTION] Completion based on another arg

### ISSUE THREAD

**Issue by stijnb1234** [aikar/commands#307]
Is it possible to base a completion on another argument?

This is my command: /shop getitem <Shop> <Item>
Every shop has its own items, so I want to base the items on the shop the user has supplied.

Is this possible?

**Comment by JOO200** [comment]
You can use context.getContextValue(Class) in the completion handler.

You need argument for the Shop in your command signature, make sure it's before the Item context.
e.g.
```java
        commandManager.getCommandCompletions().registerCompletion("shopItems", c -> {
            Shop resolved = c.getContextValue(Shop.class);
            return resolved != null ? resolved.getItems() : Collections.emptyList();
        })
```

For more stuff I suggest joining the discord.

**Comment by stijnb1234** [comment]
> You can use context.getContextValue(Class) in the completion handler.
> 
> You need argument for the Shop in your command signature, make sure it's before the Item context.
> e.g.
> 
> ```java
>         commandManager.getCommandCompletions().registerCompletion("shopItems", c -> {
>             Shop resolved = c.getContextValue(Shop.class);
>             return resolved != null ? resolved.getItems() : Collections.emptyList();
>         })
> ```
> 
> For more stuff I suggest joining the discord.

Thanks. The Shop is no object, but a String. The items are connected with the name of the shop in a HashMap.
How can I get the full string the sender entered on a specific arg?
