### ISSUE TITLE
Default autocompletion doesn't correctly

### ISSUE THREAD

**Issue by Pablete1234** [aikar/commands#310]
Currently, if you have a command without a specified completion (no annotation) it will stay as an empty string autocompletion, which does NOT autocomplete with default command completions.

When creating the registered command the `@CommandCompletion` is , it is retreived with `DEFAULT_EMPTY`:
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/RegisteredCommand.java#L96

Later, when resolving the completion, it will never be `null`, as it will instead be an empty string:
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/CommandCompletions.java#L188

A simple command to test this out:

```java
@CommandAlias("test")
public class TestCommand extends BaseCommand {
    @Subcommand("player")
    // @CommandCompletion("@players") // Works when this is set, doesn't when ommitted
    public void test(CommandSender sender, @Flags("other") Player player) {
        sender.sendMessage("Passed player: " + player.getName());
    }
}
```

The result will be no tab completion for this other player, even though there is a default completion for player that should tab-complete.

**Comment by stijnb1234** [comment]
Use the OnlinePlayer class (https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/bukkit/contexts/OnlinePlayer.java) instead of the Player class.

**Comment by Pablete1234** [comment]
@stijnb1234 Both Player and OnlinePlayer have the same default autocompletion:

https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitCommandCompletions.java#L91

There should be no difference in how they're autocompleted by default
