### ISSUE TITLE
Bitdefender detects acf-paper as trojan

### ISSUE THREAD

**Issue by JanTuck** [aikar/commands#316]
https://i.imgur.com/BDGw6m3.png

**Comment by electronicboy** [comment]
I think you need a better AV solution

**Comment by JanTuck** [comment]
> I think you need a better AV solution

It's not even in paranoia mode, like ;(

**Comment by aikar** [comment]
nothing much i can do about that, but you may want to scan full system incase you were infected by a trojan and it injected itself into random jars in an attempt to re-infect your system if it got removed.

**Comment by relavis** [comment]
Unfortunately experiencing this same issue with any of my plugins that use ACF.

**Comment by stijnb1234** [comment]
Tested the latest acf-paper JAR from the Maven repo with VirusTotal. No weird things found.
https://www.virustotal.com/gui/file/76387471fc0daa3e0b523485a6fb530f1cc269b9d6b01a8ee902ca6dea0df033/detection
