### ISSUE TITLE
Add Command-"Flags"

### ISSUE THREAD

**Issue by MCMDEV** [aikar/commands#317]
My idea would be to add command-flags, by which I mean options which can be put anywhere into the arguments and start with a signaling characters, a key and then a value. For example: -k value or --key value.
If the key is not specified, a default value will be processed which can be specified in the annotation. Boolean flags can be shortened to just the key, assuming that if only the key is given the value should be true, otherwise its false.
If a command has multiple boolean flags, they can be grouped by using just the signaling character followed by all the desired boolean flags without any spaces. For example: -abc instead of -a -b -c.
The advantage flags have over optional parameters is that they can be added in any order and without having to set the previous optional parameter if multiple flags are used. This allows commands with many options to be typed a lot faster and allows developers to add way more options without annoying users.
I know its a big thing that probably requires restructuring of the entire parsing system but it might be something to tackle for a major release.

**Comment by willies952002** [comment]
Fair chance this relates to #150

**Comment by MCMDEV** [comment]
Oh sorry, my bad
