### ISSUE TITLE
[Suggestion/Idea] Easier command creation.

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#32]
It would be easier to register the root command instead of this: 
`@CommandAlias("root|r")`
like this: `CommandManager cm = new CommandManager(this, "Prefix tag", "basepermission", "root", "r", "rootaliases")`

Then you could register subcommands like this:
```
cm.loadCommandClass(MainCommand.class);
cm.loadCommandClass(new MyCommand(this));
```
*This is just a suggestion/idea*

* * * * 
@Stumblinbear made an api like this:
* https://gist.github.com/Stumblinbear/c27f1fe584c130690b8f

**Comment by aikar** [comment]
That is insanely more complicated than simply adding an annotation.
A manager simply is responsible for attaching commands to a plugin.

Attaching a permission to multiple classes is as simple as an annotation, and the new Command Replacements feature simplifies the repetition of that node, as well as solving the repetition of root aliases too.

I recommend people move away from single commands per class and bundle relevant subcommands into the same class, and break up only when the sub commands start to form their own sub groupings.

See: https://github.com/aikar/commands/wiki/Command-Organization

**Comment by aikar** [comment]
Also to add, it is a design goal that a Command Class should declaratively define its expectations. By assigning permission nodes externally at the manager level, looking at the class file no longer sets expectations of permissions required.

Same for root commands.
