### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by corentingosselin** [aikar/commands#323]
This would be fun if we could change the command via any sort of configuration because annotations do not allow that :S  
So we could set the command with something like:  
`CMD.getRegisteredCommands().forEach(r -> r.setCommand(config.command));`

**Comment by RoinujNosde** [comment]
You can do that with command replacements:
https://github.com/aikar/commands/wiki/Command-Replacements

**Comment by corentingosselin** [comment]
Nice ! my bad I misunderstood the replacement feature, thanks !
