### ISSUE TITLE
Timings Error

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#33]
`12.05 15:31:15 [Server] WARN org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP 12.05 15:31:15 [Server] WARN at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.TimingType$1.newTiming(TimingType.java:11) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.TimingManager.of(TimingManager.java:62) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.RegisteredCommand.getTiming(RegisteredCommand.java:214) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.executeCommand(BaseCommand.java:393) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.executeSubcommand(BaseCommand.java:471) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.BaseCommand.execute(BaseCommand.java:330) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.afc.RootCommand.execute(RootCommand.java:71) 12.05 15:31:15 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) 12.05 15:31:15 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) 12.05 15:31:15 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 12.05 15:31:15 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) 12.05 15:31:15 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) 12.05 15:31:15 [Server] WARN at java.lang.Thread.run(Thread.java:745) 12.05 15:31:15 [Server] WARN org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP 12.05 15:31:15 [Server] WARN at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.SpigotTiming.<init>(SpigotTiming.java:11) 12.05 15:31:15 [Server] WARN at hu.tryharddevs.advancedkits.utils.timings.lib.TimingType$1.newTiming(TimingType.java:11)
`

**Comment by aikar** [comment]
Err was there any other errors before that for ACF?

You're on Paper but not getting the V2 Handler.

**Comment by TryHardDood** [comment]
An user sent it to me. I asked him to open a ticket on github with more details, still waiting for him.
But I thought I open one here incase you can find the problem.

**Comment by aikar** [comment]
Opened https://github.com/aikar/minecraft-timings/issues/1, will close this when the new version is pulled to ACF.

**Comment by aikar** [comment]
Please add new feedback on that other issue.

**Comment by aikar** [comment]
This is actually a bug in your build script

`relocate 'co.aikar.timings', 'hu.tryharddevs.advancedkits.utils.timings'`

This should be:
`relocate 'co.aikar.timings.lib', 'hu.tryharddevs.advancedkits.utils.timings'`

The Timings Library is under .lib, you're relocating references to the actual Timings API so it can't find the class.

Also you mispelled ACF here :P `relocate 'co.aikar.commands', 'hu.tryharddevs.advancedkits.utils.afc'`
