### ISSUE TITLE
Currently 1.17 Support is still missing

### ISSUE THREAD

**Issue by CloudeLecaw** [aikar/commands#331]
We are missing this plugin in our list since we changed to spigot 1.17 Version for our server.
We need to gamebox to make our self happy aggain <3

**Comment by JOO200** [comment]
Not sure what's your problem. Acf should work fine on 1.17 as there are no breaking changes in the command api from bukkit.

If you're unable to start your plugin with 1.17 please provide your logs.

Take note that acf is not a plugin. It's a command framework which is included by some plugins.

**Comment by CloudeLecaw** [comment]
ohh dam.. it was a bit late..i might landed in the wrong github :D..

Sorry about that
