### ISSUE TITLE
Using world as parameter

### ISSUE THREAD

**Issue by mfnalex** [aikar/commands#339]
Hi, I have a question^^

When using
```java
public static void onCommand(Player player, World world)
```
I assumed that a player has to enter a valid world name as first parameter, and also that the world names are tab-completeable. The world is correctly detected when a player enters a valid world name, however when just entering "asd", the world parameter just returns the player's world.

Is this expected behaviour? How can I force the user to enter a valid world name?

THanks!

**Comment by RoinujNosde** [comment]
That's expected.

To force a valid world you could try annotating the World parameter with `@Values("@worlds")`.

If that doesn't work, you can override the World context with your own.

**Comment by mfnalex** [comment]
Thanks!
