### ISSUE TITLE
MinecraftKey / NamespacedKey Context Resolver

### ISSUE THREAD

**Issue by willies952002** [aikar/commands#34]
This would allow for providing a command with a `MinecraftKey` / `NamespacedKey` (ex.: `minecraft:stone`) as well as a few command completions (blocks, items, achievements/advancements, etc.)

**Comment by aikar** [comment]
We can't do completions as no API exists to even know the keys available, and we will not be reflecting into NMS EVER on ACF (Only OBC).

But NamespacedKey should now be avail IF running 1.12. Added some version detection.
