### ISSUE TITLE
Question: Is non-strict command tab completion possible?

### ISSUE THREAD

**Issue by harvanchik** [aikar/commands#344]
Is it possible to have tab completion in a command, but also allow any value to be entered?

For example, when tab completing, a few completions show up, but the player can enter any value and the it will still work and no throw the "must specify one..." error.

**Comment by RoinujNosde** [comment]
Don't use `@Values`

**Comment by harvanchik** [comment]
> Don't use `@Values`

Oh, super easy.  Thanks!
