### ISSUE TITLE
Maven: Could not find artifact

### ISSUE THREAD

**Issue by mpschorr** [aikar/commands#345]
Hello, I'm having an issue when trying to import commands as a dependency.
I'm using IntelliJ IDEA Community Edition 2020.2.2
Hitting the "Reload All Maven Projects" button in the Maven tab is what generates the error.

The error I'm getting in IntelliJ is `Could not find artifact co.aikar:acf-spigot:pom:0.5.0 in aikar (https://repo.aikar.co/content/groups/aikar/)`

and the error I'm getting when trying to run `mvn clean package` is `Could not resolve dependencies for project ga.jeelzzz:GenJ:jar:1.0-SNAPSHOT: Failure to find co.aikar:acf-spigot:jar:0.5.0 in https://repo.aikar.co/content/groups/aikar/ was cached in the local repository, resolution
will not be reattempted until the update interval of aikar has elapsed or updates are forced`.

I'm new to using Maven/Java, so please keep that in mind with your answers.

pom.xml:
```xml
<repositories>
    <repository>
        <id>aikar</id>
        <url>https://repo.aikar.co/content/groups/aikar/</url>
    </repository>
    <repository>
        <id>spigotmc-repo</id>
        <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
    </repository>
    <repository>
        <id>sonatype</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>co.aikar</groupId>
        <artifactId>acf-spigot</artifactId>
        <version>0.5.0</version>
    </dependency>
    <dependency>
        <groupId>org.spigotmc</groupId>
        <artifactId>spigot-api</artifactId>
        <version>1.17.1-R0.1-SNAPSHOT</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>ga.jeelzzz</groupId>
        <artifactId>MarbleLib</artifactId>
        <version>1.0-SNAPSHOT</version>
    </dependency>
</dependencies>
```

**Comment by chickeneer** [comment]
https://github.com/aikar/commands/blob/master/docs/README.md#:~:text=bukkit%3A%20acf-bukkit%20(for%20targetting%20bukkit%2Fspigot)

You need to use acf-bukkit. That does look like a "bug" in that bukkit api is no longer a valid api target. But there also isn't any spigot api which benefits ACF - so the distinction really is not necessary at this point.

Leaving open, as it is possible we should revisit the naming of that module. But it makes no functional difference.

**Comment by mpschorr** [comment]
That makes sense that it would be a naming issue, however I'm still having the issue. All I've changed is the artifactId in the dependency.

Getting `Could not find artifact co.aikar:acf-bukkit:pom:0.5.0 in aikar (https://repo.aikar.co/content/groups/aikar/)` in IntelliJ
and `Could not resolve dependencies for project ga.jeelzzz:GenJ:jar:1.0-SNAPSHOT: Failure to find co.aikar:acf-bukkit:jar:0.5.0 in https://repo.aikar.co/content/groups/aikar/ was cached in the local repository, resolution
will not be reattempted until the update interval of aikar has elapsed or updates are forced` with `mvn clean package`. Thank you for your earlier response!

**Comment by chickeneer** [comment]
Have you tried using 0.5.0-SNAPSHOT?

**Comment by mpschorr** [comment]
That worked, thank you! I was looking through the repo files and saw that there wasn't a 0.5.0-SNAPSHOT one, and forgot to change the version when I changed the artifactId.
