### ISSUE TITLE
Doesn't work on Java 17

### ISSUE THREAD

**Issue by Fernthedev** [aikar/commands#353]
Attempting to use ACF on a Paper 1.18.1 server (build `#69` as of writing), causes this exception to be thrown. As far as I can tell, this shouldn't happen on the [latest according to Spigot's source](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0003-Spigot-Timings.patch#342-350) though I have not verified if this is the case.

```
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "org.spigotmc.CustomTimingsHandler.getCallerClass" is null
--
2 | at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:79) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-68]
3 | at com.github.Fernthedev.preferences.acf.lib.timings.SpigotTiming.<init>(SpigotTiming.java:11) ~[FCommands-1.2.jar:?]
4 | at com.github.Fernthedev.preferences.acf.lib.timings.TimingType$1.newTiming(TimingType.java:11) ~[FCommands-1.2.jar:?]
5 | at com.github.Fernthedev.preferences.acf.lib.timings.TimingManager.of(TimingManager.java:72) ~[FCommands-1.2.jar:?]
6 | at com.github.Fernthedev.preferences.acf.lib.timings.TimingManager.of(TimingManager.java:38) ~[FCommands-1.2.jar:?]
7 | at com.github.Fernthedev.preferences.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:98) ~[FCommands-1.2.jar:?]
8 | at com.github.Fernthedev.preferences.acf.PaperCommandManager.<init>(PaperCommandManager.java:35) ~[FCommands-1.2.jar:?]
9 | at com.github.fernthedev.fernapi.server.spigot.FernSpigotAPI.onEnable(FernSpigotAPI.java:35) ~[FCommands-1.2.jar:?]
```

Removing timings manually from the jar does not help either. I'm out of ideas, feel free to throw them onto me

**Comment by chickeneer** [comment]
There's gotta be some more information on this issue? ACF in our usage works fine on Paper 1.18.1 for us and on Java 17. I am willing to do some more investigation on this issue as we don't necessarily use every feature of ACF - just  would want to know what exactly is on your FernSpigotAPI.java:35 line.

**Comment by Fernthedev** [comment]
Alright, good to know that I'm probably doing something wrong here. [Here's the line](https://github.com/Fernthedev/FernAPI/blob/761bc7cd470092fe4dd2b1271fb229cdb25685d0/spigot/src/main/java/com/github/fernthedev/fernapi/server/spigot/FernSpigotAPI.java#L39)

Perhaps it's something to do with my shading or cache? No idea honestly. Running on distro provided OpenJDK 17
```
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)
``` 
Ubuntu 20.04.3 LTS x86_64

**Comment by chickeneer** [comment]
I wonder if it is related to shading. As we actually don't actually shade acf in due to the uniqueness of 'us' being the creators/maintainers of the repo and using few 3rd party plugins. Going to toy with shading and see if that can reproduce the issue...

**Comment by chickeneer** [comment]
Looking in the CustomTimingsHandler class. It looks like to me that, that code should only be running if you are using java 8 or lower. Makes me wonder if it is the detection in that class for what java version is in use. Specifically.

           ```
 String javaVer = System.getProperty("java.version");
            String[] elements = javaVer.split("\\.");

            int major = Integer.parseInt(elements.length >= 2 ? elements[1] : javaVer);
```
Which makes it look like it could detect that you are using Java 0?

**Comment by chickeneer** [comment]
Referring to this.
https://github.com/PaperMC/Paper/blob/fd352861b05e6340a1595a6e51f035d4111aa442/patches/api/0006-Timings-v2.patch#L3625

**Comment by chickeneer** [comment]
This issue should be resolved now. Let me know if it is still an issue after updating to latest Paper.
