### ISSUE TITLE
[BUG] [Velocity] Command showing in autocomplete even when the player doesn't have permission to run it

### ISSUE THREAD

**Issue by kyngs** [aikar/commands#355]
[Context + Explanation]
I have /ban command, which has permission set to "mod.infraction.ban". Which also has some autocompletion, source here: https://bin.kyngs.xyz/meyitogobi.java
[Behavior]
When I type /b it shows up the ban command even though I do not have permission to run it. When I tab it, the internal autocompletion in it doesn't appear. (Which is fine)
![image](https://user-images.githubusercontent.com/38181667/147123969-2cc4c825-428d-4df8-88b1-fc91eccd069b.png)
![image](https://user-images.githubusercontent.com/38181667/147124008-0e6e2bee-a270-4df2-9c42-504a0ea9f000.png)

[Expected Behavior]
When I type /b, it should show nothing because I do not have permission to run it. At least, that's how it works on Paper.

**Comment by RoinujNosde** [comment]
Are `/banip` and `/ban-ip` from your plugin as well?

**Comment by kyngs** [comment]
> Are `/banip` and `/ban-ip` from your plugin as well?

Yes, they are aliases. People in the paper's discord said, that it has something to do with ACF on Velocity not using brigadier IIRC.
