### ISSUE TITLE
How to allow console to run commands

### ISSUE THREAD

**Issue by galexrt** [aikar/commands#356]
I have started using this library for Bukkit and Bungeecord where commands can be used by players and also the console for certain actions.

Currently I'm unable to run commands from the console as I always get `Error: Console may not execute this command.`.
I understand that some functionality of the plugin depends on the command sender being a player, but for "normal" commands (e.g., `/myplugin reload`) it would be great if the console could run them as well.

Is there a way to allow the console to run commands already or would this be something that is wanted to be added to the library?

**Comment by kyngs** [comment]
How does the command method look like? Make sure to use CommandSender instead of Player.

**Comment by chickeneer** [comment]
This is the message when a Player parameter is given. You need to either use the CommandSender parameter or annotate the parameter as @Optional.

**Comment by galexrt** [comment]
Thanks for the quick response! That makes sense and fixes my issue.
