### ISSUE TITLE
root commands do not work on 2+ classes

### ISSUE THREAD

**Issue by aikar** [aikar/commands#36]
scenario: 2 classes, both define CommandAlias("foo|bar|baz")

subcommand `one` is defined in first class, `two` in 2nd class.

two is not accessible and says unknown command as it routes to first

Issue here: https://github.com/TryHardDood/AdvancedKitsReloaded/issues/48

**Comment by TryHardDood** [comment]
> @aikar The problem still exists. (With the latest ACF)
![image](https://cloud.githubusercontent.com/assets/10364896/26213209/7fafde70-3bf8-11e7-9dd9-af70df2c0758.png)

**Comment by aikar** [comment]
Looks like I forgot to deploy it, it's done now.

**Comment by TryHardDood** [comment]
Thanks :)
