### ISSUE TITLE
[Question] Argument names in-game

### ISSUE THREAD

**Issue by iAmMeteros** [aikar/commands#367]
Hey there! I want players to be able to see the argument names above the command line, as they do with `<name>` in the attached screenshot. In this case, the arguments do not need autocompletion. How can I implement this?
![javaw_gkbsZjVX6H](https://user-images.githubusercontent.com/46625607/167429904-39ade725-e0a1-4846-a9dd-5253513e40f1.png)

**Comment by RoinujNosde** [comment]
```java
manager.enableUnstableApi("brigadier");
```

**Comment by iAmMeteros** [comment]
> ```java
> manager.enableUnstableApi("brigadier");
> ```

After several attempts, I could not achieve the desired effect. When you press the spacebar, an empty label appears, and when typing, the same text appears on top.

![изображение](https://user-images.githubusercontent.com/46625607/167444662-7e60a47f-4140-4b7d-a3c6-2abc1c9f0fae.png)

![изображение](https://user-images.githubusercontent.com/46625607/167444859-c5bfad80-4770-453e-8532-fc6f4b6f6b8c.png)

Here is my code:

Main class:

```
public void onEnable() {

        ...
        
        BungeeCommandManager manager = new BungeeCommandManager(this);
        manager.registerCommand(new MyCommand());

        manager.enableUnstableAPI("brigadier");
    }
```

MyCommand class:
```
@CommandAlias("somecommand")
@SuppressWarnings("unused")
public class MyCommand extends BaseCommand {
    @Default
    @Syntax("<sometext>")
    public void execute(ProxiedPlayer player, String text) {
        ...
    }
}
```

Maybe I should add something in the argument declaration..?

**Comment by JOO200** [comment]
The brigadier implementation is currently only awailable for Paper.
It's not possible in BungeeCord.

**Comment by iAmMeteros** [comment]
Got it, thanks for the help!
