### ISSUE TITLE
1.19.1 with brigidaer breaks certain commands

### ISSUE THREAD

**Issue by MWHunter** [aikar/commands#372]
I've uploaded an example repo with minimal reproduction:

https://github.com/MWHunter/AcfTest

Try running /test2 b 1 with brigadier on 1.19.1 enabled, versus disabled.  The command doesn't work when it is enabled on 1.19.1.  Pre-1.19.1 everything works fine.

**Comment by chickeneer** [comment]
I have deployed a fix for this issue. Obviously, let me know if this has caused a separate issue. Although I am fairly confident about it.

**Comment by chickeneer** [comment]
I believe that other brigadier issues exist.  Technically separate reproduction steps, but same root cause from the server software.
I will continue to be working on it.
