### ISSUE TITLE
@Syntax doesn't work

### ISSUE THREAD

**Issue by BrainRTP** [aikar/commands#374]
Hi! I set `@Syntax` annotation to method but if i write incorrect command i have template syntax command: 
```
Usage: <c2>{command}</c2> <c3>{syntax}</c3>
```
Code:
```java

@CommandAlias("eastereggs|ee")
public class ListCategoryCommand extends BaseCommand {

    @Subcommand("list")
    @CommandPermission("eastereggs.admin")
    @Syntax("[page]")
    @Description("List of easter eggs")
    public void onListCategory(Player player, @Optional @Single @Default("1") Integer page) {
```
Screenshot:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/22731705/188282262-5aab3072-e027-4a32-91f3-5f1973bb1778.png">

What's wrong?

**Comment by MiniDigger** [comment]
idk about the syntax annotation, but arg1 -> page can be achieved by enabling params in the compiler, aka adding the --parameters compiler flag:
https://github.com/aikar/commands/wiki/Maven-Setup
https://github.com/aikar/commands/wiki/Gradle-Setup

**Comment by BrainRTP** [comment]
> idk about the syntax annotation, but arg1 -> page can be achieved by enabling params in the compiler, aka adding the --parameters compiler flag: https://github.com/aikar/commands/wiki/Maven-Setup https://github.com/aikar/commands/wiki/Gradle-Setup

about relocate for dradle shadow jar - these changes are present for me

**Comment by RoinujNosde** [comment]
> idk about the syntax annotation, but arg1 -> page can be achieved by **enabling params in the compiler**, aka adding the --parameters compiler flag:

```groovy
compileJava {
    options.compilerArgs += ["-parameters"]
    options.fork = true
    options.forkOptions.executable = 'javac'
}
```

**Comment by BrainRTP** [comment]
> ```groovy
> compileJava {
>     options.compilerArgs += ["-parameters"]
>     options.fork = true
>     options.forkOptions.executable = 'javac'
> }
> ```

Oh, my bad. I will try it

**Comment by BrainRTP** [comment]
It's work. Thank you guys!

**Comment by kyngs** [comment]
BTW: You can also use the @Name annotation directly on the parameter to specify a custom argument name.

**Comment by name** [comment]
@kyngs No problem! You're not the only one aha
