### ISSUE TITLE
Allow translatable contents in @CommandCompletion

### ISSUE THREAD

**Issue by kyngs** [aikar/commands#377]
Currently using \@@<key>} for translatable contents only works in `@Description` and `@Syntax`, I would like it to be added to `@CommandCompletion`.

EDIT: Sorry, I've pinged two guys.

**Comment by chickeneer** [comment]
Am deploying this out now. As mentioned in my commit message.

> Yes, people should register a completion so it is per-issuer but non-registered
static completions would benefit from the replacements system

Good issue :)

**Comment by chickeneer** [comment]
Note for anyone that looks at this issue. An error was made in the commit message. It isn't "Translating" It is a static replacement.

Translatable messages occur when messaging out. ACF doesn't have command registration support per locale. (So everyone has the same subcommands, static completions, etc).
Whereas the replacement system allows you to one-time replace command annotations at the time of command registration.

Examples at time of posting this comment.
how one would register the replacements.
https://github.com/aikar/commands/blob/master/example/src/main/java/co/aikar/acfexample/ACFExample.java#L56

Example of them in use in defining a CommandAlias.
https://github.com/aikar/commands/blob/master/example/src/main/java/co/aikar/acfexample/SomeCommand.java#L76
Or as a CommandPermission
https://github.com/aikar/commands/blob/master/example/src/main/java/co/aikar/acfexample/SomeCommand.java#L143
Or as a CommandCompletion
https://github.com/aikar/commands/blob/master/example/src/main/java/co/aikar/acfexample/SomeCommand.java#L160
