### ISSUE TITLE
Not related to this project but repository.

### ISSUE THREAD

**Issue by portlek** [aikar/commands#379]
whenever i use your repository for this framework or anything else out there, it always download metadata xml file. normally syncing my intellij idea takes 3 seconds without your command framework:
![image](https://user-images.githubusercontent.com/12835420/203999113-4b8ca89b-e223-4653-afe8-105ea6d21d30.png)
![image](https://user-images.githubusercontent.com/12835420/203999146-e9fd3972-4dbf-4d3a-b80a-c1702b079312.png)
whenever i comment out one of the library that uses aikar's repository it takes too long because it always download the xml files again and again:
![image](https://user-images.githubusercontent.com/12835420/203999295-47b0a61c-482a-482b-9c00-66d21c82ad1d.png)
and this is not a single module project and whenever i open the other modules this takes 3-10 minutes to sync.
![image](https://user-images.githubusercontent.com/12835420/203999313-f31b2b73-ad17-472b-85af-59bd2755a834.png)

i guess the problem with the repository is that it always checks anything new for the snapshot builds. i've other libraries which have snapshot version too but they don't download again and again until 1 day pass. i believe this is adjustable in your repository settings, or if you guys have any idea to stop that in gradle lmk ^.^

**Comment by JOO200** [comment]
Can you provide a simple Gradle project with that issue?

E.g. a single gradle build file. I can't see what you're exactly using because your "smolApi" call is not gradle api.

**Comment by portlek** [comment]
ok, i've simplified the issue and reproduce it with gradle apis too. but i've found the issue is not about this repository but these ones:
`https://repo.dustplanet.de/artifactory/libs-release-local/`
`https://repo.dustplanet.de/artifactory/ext-release-local/`
![image](https://user-images.githubusercontent.com/12835420/204003945-896fccd1-375f-4c9e-bfe4-5b2fabd54867.png)
whenver i comment those out it does not download the xml files again. i guess i need to do some refactor to not use those repositories.
