### ISSUE TITLE
Creating Timings deprecated warnings - Paper planning to remove Timings functionality

### ISSUE THREAD

**Issue by Archy-X** [aikar/commands#385]
Registering commands as of Paper 1.19.4 Build 478 generates warnings related to timings being deprecated. Paper plans on removing Timings functionality and replacing it with Spark, so any use of the Timings API must be removed or replaced (https://github.com/PaperMC/Paper/issues/8948).
<img width="1180" alt="Screenshot 2023-03-29 at 10 32 11 PM" src="https://user-images.githubusercontent.com/63976867/228713271-b35e79c7-622e-49df-a66a-88a639e8f5b3.png">

**Comment by chickeneer** [comment]
^ I have committed and deployed a change to ACF to resolve this warning, as linked in the above commit.

I kept the getTimings() field on the CommandManager, but removed all creations of creations of the timings themselves by the commands. This has the consequence of also removing for Bukkit/Spigot versions of the server, or on older server versions. I think this is the right call though. One does have the ability to re-add in these timings calls if it is a feature they desire for their plugin.

I have deployed this to 0.5.1-SNAPSHOT, which was already the latest. I did not bump versions. I would anticipate next version bump will remove that getTimings() method which will have no useful purpose in the paper pipeline here soon.

Obviously let me know if anyone has any concerns about me executing this change.

Most people should be able to just recompile their plugin to fix this warning.
