### ISSUE TITLE
Add support to Folia if it possible

### ISSUE THREAD

**Issue by Aitooor** [aikar/commands#386]
Folia url: https://github.com/PaperMC/Folia

Thanks 😄

**Comment by chickeneer** [comment]
Have you tried using this in a Folia plugin? I guess, I don't immediately know what is incompatible. Feel free to report particular issues that need addressed.

**Comment by creatorfromhell** [comment]
> Have you tried using this in a Folia plugin? I guess, I don't immediately know what is incompatible. Feel free to report particular issues that need addressed.

I have tested it and here is the resulting error log related to ACF:

```
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[folia-1.19.4.jar:git-Folia-"7072994"]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[folia-1.19.4.jar:git-Folia-"7072994"]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[folia-1.19.4.jar:git-Folia-"7072994"]
	at net.tnemc.libs.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:125) ~[Folia-0.1.2.0-PRE-1.jar:?]
	at net.tnemc.libs.acf.PaperCommandManager.<init>(PaperCommandManager.java:35) ~[Folia-0.1.2.0-PRE-1.jar:?]
```

**Comment by MiniDigger** [comment]
cant use the bukkit scheduler on folia, should prolly just allow disabling it I guess https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java#L125

**Comment by creatorfromhell** [comment]
> cant use the bukkit scheduler on folia, should prolly just allow disabling it I guess https://github.com/aikar/commands/blob/master/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java#L125

It's also in the ACFBukkitListener too.

**Comment by chickeneer** [comment]
Alright. I will take a look at the best way to add folia support. Would prefer not to create an extra module for it, but that may very well end up being the route that is needed. Probably extending the paper module and overriding the things that are breaking.

**Comment by creatorfromhell** [comment]
> Alright. I will take a look at the best way to add folia support. Would prefer not to create an extra module for it, but that may very well end up being the route that is needed. Probably extending the paper module and overriding the things that are breaking.

If you're interested in taking a look at a PR I'm about to make for it after testing I'll have it ready shortly.

**Comment by chickeneer** [comment]
For sure. As long as you don't have anything too crazy in it, I am on board with taking a PR.

**Comment by creatorfromhell** [comment]
> For sure. As long as you don't have anything too crazy in it, I am on board with taking a PR.

I'll try my best not to do anything too outlandish.

**Comment by creatorfromhell** [comment]
> For sure. As long as you don't have anything too crazy in it, I am on board with taking a PR.

I made a PR for it #387 . I tried not making a new module for it, but the two Bukkit Dependencies were fighting it out in the paper module. However, I was able to keep the new module down to two classes.
