### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by vortexthedev** [aikar/commands#396]
When you create a command using bungee acf it always says that you dont have permission when you execute it
even if the command doesnt have any permission set using @CommandPermission

**Comment by vortexthedev** [comment]
![image](https://github.com/aikar/commands/assets/72511773/d0211396-c8b6-4a3f-9ef9-40c460f916f9)
I didn't specify any permissions by @CommandPermission annotation and I use LuckPerms.
I can't even execute the commands from console

**Comment by Joo200** [comment]
Use the verbose mode from LuckPerms to find the missing permission

**Comment by vortexthedev** [comment]
Fixed! Thanks!
