### ISSUE TITLE
Inner classes on Kotlin do not register

### ISSUE THREAD

**Issue by skyeredwood** [aikar/commands#404]
I'm trying to register a command using Kotlin & Paper, however registering subcommands via an inner class doesn't register the subcommands. In the example below, the `root` method (aka `/command about`) is registered but the other method inside of a nested class (`/command inner my-subcommand`) doesn't appear in tab-complete and returns an error.

All documentation shows inner classes being marked as `static` (Java keyword), the Kotlin equivalent of which is declaring the class an `object` instead. However, this doesn't change the outcome. The observed behaviour also doesn't change when adding the `inner` modifier to a class.

```kt
@CommandAlias("command")
class MyCommand : BaseCommand() {

    @Default
    @Subcommand("about")
    fun root(player: Player) {
        // ...
    }
    
    @Subcommand("inner")
    class InnerCommands {
        @Subcommand("my-subcommand")
        fun mySubCommand(player: Player) {
            // ...
        }
    }
}
```

I'm using `acf-paper` version `0.5.1-SNAPSHOT` and Paper API `1.20.2-R0.1-SNAPSHOT` if that clarifies anything.

**Comment by skyeredwood** [comment]
Update: adding the `@CommandAlias` annotation (with the same arguments as the outer class) to the inner class doesn't affect it either, it seems that the command manager just does not recognise that the class even exists

**Comment by ocald21** [comment]
Make sure your inner class also inherits the BaseCommand abstract class as well as marking the inner class with the inner keyword.

**Comment by skyeredwood** [comment]
Thank you; this combined with the @CommandAlias on the inner class fixed my issue.
