### ISSUE TITLE
BukkitCommandManager readPlayerLocale wrong for 1.20.2 and above

### ISSUE THREAD

**Issue by C0D3-M4513R** [aikar/commands#405]
https://github.com/aikar/commands/blob/26d72f27c6dd455d047d3aa5c8f4cf89124cf139/bukkit/src/main/java/co/aikar/commands/BukkitCommandManager.java#L326

up to 1.20.1:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/EntityPlayer.patch?until=f7fa6d9935148ff2864727d6765b89485a3d42ce&untilPath=nms-patches%2Fnet%2Fminecraft%2Fserver%2Flevel%2FEntityPlayer.patch#889

1.20.2 and above:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/level/EntityPlayer.patch?until=28c10232864804265dd3fa4e2008a55e1718b128&untilPath=nms-patches%2Fnet%2Fminecraft%2Fserver%2Flevel%2FEntityPlayer.patch#46

and as for `player.locale()`, I cannot find a reference to that under the official Bukkit classes?
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/entity/Player.java

**Comment by mfnalex** [comment]
Player#locale() is a paper thing.

I also never understood the overly complicated version currently used in 0.5.1-SNAPSHOT to read the locale - what's wrong with Player#getLocale()?

I'm using this and it seems to be working fine: https://github.com/SpigotBasics/acf/commit/3ce7f7a1119b51094829a9e98a0abbfadd98a6a4#diff-c44eb8b7e2e56565669392163af057719d059448c3c81e6f40021fc47cc66ea8

**Comment by DeathRealms** [comment]
I believe Player#getLocale() wasn't added until 1.12

**Comment by chickeneer** [comment]
I have deployed a change that probably fixes this.

**Comment by mfnalex** [comment]
Thanks, the error message is now gone! Have a nice day!
