### ISSUE TITLE
Properly support custom sender objects

### ISSUE THREAD

**Issue by MiniDigger** [aikar/commands#48]
```
18:43> ~Aikar>I do want to add a "SenderAwareOnlyResolver"
18:43> ~Aikar> that never consumes input
18:44> ~Aikar> then we know for sure that its optional and not put it in syntax strings
```

**Comment by aikar** [comment]
@MiniDigger we do now have IssuerOnlyContextResolver. I believe this satisfies your need.

Add a context if your custom issuer class, map the player object to your custom class, and ensure its registered IssuerOnly (so no input should ever be consumed)
