### ISSUE TITLE
register bound to plugin objects

### ISSUE THREAD

**Issue by aikar** [aikar/commands#5]
right now its hard coded into "empire" name space. need to figure out how were going to do registration.

Remove automatic registration on instantiation and make Commands.register(plugin, instance) ?

**Comment by electronicboy** [comment]
For this one we could just enforce passing of a plugin over to BaseCommand, from the name of the method that's just used for registering a plugin:command name, however, I say this at 7:37am, so feel free to correct me on that.

The fun itself comes into "How do we transform a system designed for a single instance into something that won't die when multiple people use this system in their plugins on one server", This especially becomes relevant in regards to issues such as #3 and #4
