### ISSUE TITLE
Optional resolvers are bugged 

### ISSUE THREAD

**Issue by Williambraecky** [aikar/commands#50]
Since e50e90637f606f59957d90919f1992efcb933edf ACF tries to resolve Optional parameters

**Comment by chickeneer** [comment]
Could you clarify what the issue is?
I presume the relevant commit is this one: 87995f03df8ae0fcca632619c43542f6b37a3a10 instead of the one linked.

**Comment by Williambraecky** [comment]
Indeed, i missclicked my copy.
The issue was that optional Parameters would try to resolve resulting in npes because there simply was nothing to resolve.
However this is fixed since aikar accepted my pr
