### ISSUE TITLE
Google Cache multiple versions compatibility..

### ISSUE THREAD

**Issue by Stawlker** [aikar/commands#52]
Hello, can you add compatibility with versions 1.7 to 1.12 ? 

Your ACFPatterns class causes errors due to the LoadingCache and CacheLoader classes. Here is a class that could help you do what I ask: 
- [UserMap [Essentials]](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/UserMap.java)

I would like you to do this because I use this fork in my Stawlkalibur plugin, link here: https://www.spigotmc.org/resources/stawlkalibur-almost-ready-only-java-8.12510/

**Comment by aikar** [comment]
Can you detail what the problem is? I actually did recently try to fix this.

https://github.com/aikar/commands/commit/2ea2303444f45adecd0b6298caa6940163433b08#diff-357e4854869b2e21c38b1b437f11095aL52

**Comment by Stawlker** [comment]
The methods build() and get() of the com.google.common.cache.Cache class cause errors in version previous to 1.11 because the version of Google Guava used in your PaperSpigot dependency is not the same. If you want, I can give you my CacheUtil class so that your fork is compatible with all the versions of Minecraft. Otherwise you can put me collaborators so that I add the methods to the ACFUtils class.

**Comment by aikar** [comment]
Give me the exception/logs.

You can PR if you know how to make it work on both, but i want to see the exception first as I don't understand why this doesn't work since I'm using Guava 15 which is what 1.7 uses and these API's look the same as the latest guava.

**Comment by Stawlker** [comment]
I give you the logs when I would be on my computer but the latest version of PaperSpigot 1.7.10 is compiled with Google Guava 1.10.

**Comment by aikar** [comment]
Interesting, OK I will see what I can do tonight. MC client used Guava 15 in 1.7 so I targeted that... 

I might just drop the cache map for patterns. I don't even really need it.

**Comment by Stawlker** [comment]
Yes, I think is the best solution.

Error logs: http://prntscr.com/fmwn6d
