### ISSUE TITLE
CommandCooldown Annotations..

### ISSUE THREAD

**Issue by Stawlker** [aikar/commands#57]
**Can you add a system that allows you to put a cooldown on commands?**

With a default value (in seconds) and an other value that can be reassigned to the commands you want.

**Example:**

```java
commandManager.setDefaultCommandCooldown(2.5);

@Default
@CommandCooldown(5.0)
@CommandPermission("staff.example")
@UnknownHandler
public void onCommand(Player player) {

}
```

**Comment by TryHardDood** [comment]
That's unneeded. If you want to do that do it in your code.

**Comment by Stawlker** [comment]
No it is not useless. Not against your message though.

**Comment by TryHardDood** [comment]
All right.. it's not useless but you can easily do it without the
annotation.

**Comment by Stawlker** [comment]
I know but I find it more compact to have everything in the same api.

**Comment by Stawlker** [comment]
https://github.com/aikar/commands/issues/58
