### ISSUE TITLE
Semantics: rename @UnknownHandler to @CatchAll

### ISSUE THREAD

**Issue by simpleauthority** [aikar/commands#70]
This would make no functional difference. This is just a suggestion to rename the wording of the UnknownHandler interface to CatchAll, to better describe its functionality. Since UnknownHandler acts as the default route for those inputs which can't otherwise be routed, CatchAll would make more sense since it catches those which can't be routed. Both make sense as is, but, in my opinion, CatchAll is clearer.

Discuss?

**Comment by aikar** [comment]
Agreed, will rename whenever something worthy of an API break occurs.

Or I might add it sooner and make both function and mark unknown deprecated.

**Comment by aikar** [comment]
Closed in a14b30c
