### ISSUE TITLE
Add annotation for matching an arg with regex

### ISSUE THREAD

**Issue by GreenMeanie** [aikar/commands#76]
If you run a command, and you need the player to input the information in a specific format: "days:12".

This would be in the command's method: @Matches("RegEx") String time

**Comment by aikar** [comment]
Id like to see it a little more flexible, such as @Validate("regex:<pattern>")

Then, we can do multiple validators like @Validate("mcname,foo,bar") add a new registerValidator("mcname, (c) => /* validate the context */) before the Context resolvers or tab completion handlers even run.

**Comment by MiniDigger** [comment]
that way we could cache the compiled regex tho. not sure about the performance, would it be worth to have a hashmap for compiled regex patterns?

**Comment by aikar** [comment]
We have a regex cache already in the project

**Comment by aikar** [comment]
This is now satisfied with https://github.com/aikar/commands/wiki/Command-Conditions

I don't feel as if we need a pre-resolve validation method based on string input.

conditions should solve any needs of that idea.
