### ISSUE TITLE
Optional permission nodes

### ISSUE THREAD

**Issue by GreenMeanie** [aikar/commands#78]
Would it be possible to do something like:

```Java
@CommandPermission("test.permission")
public void onTest(Player player, @Optional("test.permission.optional") Player test) {}
```

**Comment by aikar** [comment]
What are you trying to do? I don't understand the request. This would reference the command sender twice

If you want to conditionally determine if the player has a permission, you should just not put the permission on the command, and check in the command body.

**Comment by GreenMeanie** [comment]
I was thinking that the base command would have one permission. Then if you
add the optional variable, you would be required to have the permission
given to the optional.

It would make it easier to have like a vanish.self permission, then a
vanish.others permission.

**Comment by aikar** [comment]
@GreenMeanie if you want to check if the target player of the command has a permission, thats something best done in the method of the command.

I dont think thats anywhere near common of a case to put into the framework.


If you're looking for 2 permissions to be required, add one to base command, one to the method. both will be required.

or @CommandPermission("foo,bar") to require both

**Comment by GreenMeanie** [comment]
Fair enough
