### ISSUE TITLE
Setting color format using CommandManager#setFormat ignores first argument

### ISSUE THREAD

**Issue by Yamakaja** [aikar/commands#82]
The method [CommandManager#setFormat](https://git.io/vNerM) gets the current color profile and iterates through its parameters, setting each value to a new one. But this method has a couple flaws:
First of all, the [MessageFormatter#setColor](https://git.io/vNeoJ) method decreases its index parameter by one if above zero and sets everything else to zero. This means that setColor(0, x) and setColor(1, x) are effectively equivalent and the first call is ignored.
Additionally it would probably be a good idea to clear the list and then to just add the new color, to cleanup leftover default colors, in case you add less than there were previously.

**Comment by aikar** [comment]
good catch, not sure on clearing.

This API was more of a help to quickly set colors. but if someone did setColor with 4 as index, then followed by 3, they either arent using index 4, or they are. either way is fine.

or they may have code .setFormat(type, 4, somethingspecial); then followed by .setformat(type, commoncolors); though could reverse the order.

Don't see it as harmful as is though.

**Comment by Yamakaja** [comment]
It sounds like there is some old API that i shouldn't be using anymore "This API was more of a help to quickly set colors.", what's the alternative?
