### ISSUE TITLE
List all subcommands

### ISSUE THREAD

**Issue by MrDienns** [aikar/commands#84]
Kon'nichiwa,

Would love to see a way of specifing one command as the "base" and if no additional parameters are provided, send a help message to the user automatically generated with all possible subcommands.

Example:
```/test```

Would result in:
```
/test 1
/test 2 <parameter>
/test 3 <parameter> <parameter>
```

I haven't seen it in the example so I assume it's not implemented (yet).

**Comment by aikar** [comment]
As @Mishyy mentioned, you can use https://github.com/aikar/commands/wiki/Command-Help for this
