### ISSUE TITLE
Dependency Injection Annotation

### ISSUE THREAD

**Issue by aikar** [aikar/commands#85]
Provide a way for the command manager to receive dependencies and provide standard dependency injection abilities

Such as

```java
manager.addDependency(Plugin.class, plugin);
manager.addDependency(MyPlugin.class, plugin);
manager.addDependency(MyObjectManager.class, objManager);

public MyCommandClass extends BaseCommand {
    @Dependency MyPlugin plugin;
    @Dependency MyObjectManager manager;
    // ... commands
}
```

On registration, ACF can fulfill the dependencies as provided, as commonly seen in more featured dependency injection frameworks.

**Comment by MiniDigger** [comment]
This is as simple as having a map<class, object> and some reflection to inject the instances, right? Might give it a try later today.

**Comment by aikar** [comment]
@MiniDigger correct

**Comment by MiniDigger** [comment]
drafted a PR for this #86
