### ISSUE TITLE
Custom Annotation Aliases

### ISSUE THREAD

**Issue by aikar** [aikar/commands#89]
Provide an API to allow users to register their own annotations to be aliases to default ACF annotations + Configurations: Flags, Conditions, CommandPermission, Subcommand

Something like 

```java
manager.registerAnnotation(CustomAnnotation.class, Conditions.class, "conditionname:conditionconfig");
manager.registerParameterAnnotation(ParameterType.class, CustomAnnotation.class, Conditions.class, "conditionname:conditionconfig");
manager.registerParameterAnnotation(ParameterType.class, CustomAnnotation.class, Flags.class, "flagconfig=flagvalue");
```

Then using `@CustomAnnotation` will be same as putting 
```java
@Conditions("conditionname:conditionconfig") @Flags("flagconfig=flagvalue")
```
 on a parameter or method

I will be personally working this issue, not looking for PR's on it.

**Comment by simpleauthority** [comment]
Do you have a branch for this?

**Comment by aikar** [comment]
yes and no, work is actively being done in master for it.

**Comment by aikar** [comment]
https://github.com/aikar/commands/blob/master/core/src/main/java/co/aikar/commands/Annotations.java

**Comment by aikar** [comment]
Note the API is not exposed in any way yet as its constantly changing (when I get time to work on it), just doing most of it in master so I can move/refactor things w/o disrupting PR's, and ensure new additions can follow the new pattern.

**Comment by kumpelblase2** [comment]
Have you considered using meta-annotations (so using annotations on annotations) for this instead? Not to mention, basic support would be trivial to implement (given the current state of the code):

In `Annotations.java#L53` if we change this:
```diff
- Annotation annotation = object.getAnnotation(annoClass);
+ Annotation annotation = getAnnotationRecursive(object, annoClass);
```
and define that function like so:
```java
    private static Annotation getAnnotationRecursive(AnnotatedElement object, Class<? extends Annotation> annoClass) {
        if(object.isAnnotationPresent(annoClass)) {
            return object.getAnnotation(annoClass);
        } else {
            for (Annotation otherAnnotation : object.getDeclaredAnnotations()) {
                final Annotation annotationRecursive = getAnnotationRecursive(otherAnnotation.annotationType(), annoClass);
                if(annotationRecursive != null) {
                    return annotationRecursive;
                }
            }
        }
        return null;
    }
```
it would already find the necessary annotations. So we could implement your given example like this:
```java
@Retention(RetentionPolicy.RUNTIME)
@Conditions("conditionname:confitionconfig")
@Flags("flagconfig=flagvalue")
public @interface CustomAnnotation {}
```
(The only additional thing that would be needed to change for `@Flags` to work like in the example is to allow that annotation to be present on annotation types, which it currently isn't allowed to. `@Conditions` would already work like this.)

This is used quite extensively in Spring/Spring Boot (a little bit of reference [here](https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model)), though Spring goes quite a bit further (for example, also allowing for properties of the combined annotation to alias for properties on the composing annotations).

**Comment by kumpelblase2** [comment]
Done now under https://github.com/aikar/commands/pull/217 . As mentioned in the commit, I excluded (as in, not allowing it on annotation types) `@Dependency` because I don't think there's any use case for combining that with any of the other annotations, but feel free to make changes if you disagree.

**Comment by aikar** [comment]
@kumpelblase2 sorry for delay on this.
is "(The only additional thing that would be needed to change for @Flags to work like in the example is to allow that annotation to be present on annotation types, which it currently isn't allowed to. @Conditions would already work like this.)" covered?

Any additional work needed still ?

**Comment by kumpelblase2** [comment]
Yes, that is covered. What I meant was that `@Flags` needed `@Target(ElementType.ANNOTATION_TYPE)` in addition to what it already had. I added that in the PR along with adding it to many other annotations that one may want to combine.

**Comment by aikar** [comment]
Ok closing then, thanks! deploying new build soon
