### ISSUE TITLE
JDA Support

### ISSUE THREAD

**Issue by aikar** [aikar/commands#90]
Provide first class support for JDA (Java Discord API)

WIP has been made.

**Comment by simpleauthority** [comment]
See #135, #136.

**Comment by simpleauthority** [comment]
See #137, #138.

**Comment by chickeneer** [comment]
I am closing this issue as the issue itself lacks the information on what was missing from implementing. Also in favor of the other issue on the topic of slash-command support.
https://github.com/aikar/commands/issues/366
