### ISSUE TITLE
Set Default Command Completion by Context/Class

### ISSUE THREAD

**Issue by aikar** [aikar/commands#96]
Similar to context, be able to set default command completions for all parameters of a context

```java
manager.getCompletions().setDefaultCompletion("@players", OnlinePlayer.class, Player.class); // Class should be varargs, 
```

When Completion is not set for a parameter on a command, then check the default map to find the default completion.

**Comment by DarkPaladinUHC** [comment]
I am going to attempt to implement this today.

**Comment by DarkPaladinUHC** [comment]
should CommandComletions#setDefaultCompletion() return the CommandCompletionHandler that is set to be default?

**Comment by DarkPaladinUHC** [comment]
If a completion id that is not registered is specified, What type of exception should be thrown? `CommandCompletionTextLookupException`?

**Comment by aikar** [comment]
this was recently finished.
