### ISSUE TITLE
IncompatibleClassChangeError when registering a command

### ISSUE THREAD

**Issue by knightzmc** [aikar/commands#97]
Hi guys. Just started using this framework, so maybe my fault, but when using BukkitCommandManager#registerCommand, I get this error
`java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class uk/knightz/knightzapi/acf/RootCommand. Method lambda$addChildShared$0(Lcom/google/common/collect/SetMultimap;Luk/knightz/knightzapi/acf/BaseCommand;Ljava/util/Map$Entry;)V at index 55 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
        at uk.knightz.knightzapi.acf.RootCommand.addChildShared(RootCommand.java:43) ~[?:?]
        at uk.knightz.knightzapi.acf.BukkitRootCommand.addChild(BukkitRootCommand.java:74) ~[?:?]
        at uk.knightz.knightzapi.acf.BaseCommand.register(BaseCommand.java:272) ~[?:?]
        at uk.knightz.knightzapi.acf.BaseCommand.registerSubcommand(BaseCommand.java:301) ~[?:?]
        at uk.knightz.knightzapi.acf.BaseCommand.onRegister(BaseCommand.java:199) ~[?:?]
        at uk.knightz.knightzapi.acf.BaseCommand.onRegister(BaseCommand.java:122) ~[?:?]
        at uk.knightz.knightzapi.acf.BukkitCommandManager.registerCommand(BukkitCommandManager.java:170) ~[?:?]
        at uk.knightz.knightzapi.acf.BukkitCommandManager.registerCommand(BukkitCommandManager.java:200) ~[?:?]
...`

(sorry for weird package names, included it in my personal API)

I'm pretty sure this is a bug, as there's nothing screaming error at me.

Here's my command class, if it helps

`
@CommandAlias("kit|kits")
public class KitCommand extends BaseCommand {
    @Subcommand("equip")
    @CommandAlias("give")
    public void onEquip(Player p, String[] args) {
        p.sendMessage("test??");
    }
    public void onCommand(CommandSender sender) {
        sender.sendMessage("test lol");
    }
}`

**Comment by aikar** [comment]
Are you running it on Java 6 or 7 by chance? ACF requires Java 8.

That's the only thing that seems to relevant to this error.

**Comment by knightzmc** [comment]
No, I'm using Java 9 (I think). This might be why?

On 3 Feb 2018 15:59, "Daniel Ennis" <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you running it on Java 6 or 7 by chance? ACF requires Java 8.

That's the only thing that seems to relevant to this error.

**Comment by aikar** [comment]
Hmm, you may need to compile your plugin for Java 8 then. 

According to some other people reporting this, It's due to shading a java8 lib into a java 9 lib.

Maybe try updating your compiler.

I don't see what I could do on ACF's side to fix this, as we will not be requiring java 9 for least a few years.

**Comment by aikar** [comment]
Are you using ASM by chance? If so what version? I saw one project apparently fixed it possibly by updating ASM.

**Comment by knightzmc** [comment]
To be honest, I don't really use it for anything apart from tiny bug fixes and just the fact that it's the latest version. OK, will downgrade. I think it's because I've got JDK 9 and JRE 8, if anyone else has this problem

On 3 Feb 2018 16:19, "Daniel Ennis" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm, you may need to compile your plugin for Java 8 then.

According to some other people reporting this, It's due to shading a java8 lib into a java 9 lib.

Maybe try updating your compiler.

I don't see what I could do on ACF's side to fix this, as we will not be requiring java 9 for least a few years.

**Comment by aikar** [comment]
Closing as this isn't a bug in ACF (just using a standard java feature....)

This needs to be solved by the Shade plugins and Compilers.

Just for data sake, are you using Gradle or Maven?
